// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: bot.proto

package botpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InboundMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	ConnectionId  int64                  `protobuf:"varint,3,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Jid           string                 `protobuf:"bytes,4,opt,name=jid,proto3" json:"jid,omitempty"` // chat JID (the sender's WhatsApp address)
	SenderJid     string                 `protobuf:"bytes,5,opt,name=sender_jid,json=senderJid,proto3" json:"sender_jid,omitempty"`
	Body          string                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboundMessage) Reset() {
	*x = InboundMessage{}
	mi := &file_bot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundMessage) ProtoMessage() {}

func (x *InboundMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundMessage.ProtoReflect.Descriptor instead.
func (*InboundMessage) Descriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{0}
}

func (x *InboundMessage) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *InboundMessage) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *InboundMessage) GetConnectionId() int64 {
	if x != nil {
		return x.ConnectionId
	}
	return 0
}

func (x *InboundMessage) GetJid() string {
	if x != nil {
		return x.Jid
	}
	return ""
}

func (x *InboundMessage) GetSenderJid() string {
	if x != nil {
		return x.SenderJid
	}
	return ""
}

func (x *InboundMessage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type ReplyChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"` // true on the final (possibly empty) sentinel chunk
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyChunk) Reset() {
	*x = ReplyChunk{}
	mi := &file_bot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyChunk) ProtoMessage() {}

func (x *ReplyChunk) ProtoReflect() protoreflect.Message {
	mi := &file_bot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyChunk.ProtoReflect.Descriptor instead.
func (*ReplyChunk) Descriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{1}
}

func (x *ReplyChunk) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ReplyChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

var File_bot_proto protoreflect.FileDescriptor

const file_bot_proto_rawDesc = "" +
	"\n" +
	"\tbot.proto\x12\x03bot\"\xb0\x01\n" +
	"\x0eInboundMessage\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12#\n" +
	"\rconnection_id\x18\x03 \x01(\x03R\fconnectionId\x12\x10\n" +
	"\x03jid\x18\x04 \x01(\tR\x03jid\x12\x1d\n" +
	"\n" +
	"sender_jid\x18\x05 \x01(\tR\tsenderJid\x12\x12\n" +
	"\x04body\x18\x06 \x01(\tR\x04body\"4\n" +
	"\n" +
	"ReplyChunk\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done28\n" +
	"\x03Bot\x121\n" +
	"\aProcess\x12\x13.bot.InboundMessage\x1a\x0f.bot.ReplyChunk0\x01BBZ@github.com/alan/ia-pipeline/whatsapp-gateway/internal/grpc/botpbb\x06proto3"

var (
	file_bot_proto_rawDescOnce sync.Once
	file_bot_proto_rawDescData []byte
)

func file_bot_proto_rawDescGZIP() []byte {
	file_bot_proto_rawDescOnce.Do(func() {
		file_bot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bot_proto_rawDesc), len(file_bot_proto_rawDesc)))
	})
	return file_bot_proto_rawDescData
}

var file_bot_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bot_proto_goTypes = []any{
	(*InboundMessage)(nil), // 0: bot.InboundMessage
	(*ReplyChunk)(nil),     // 1: bot.ReplyChunk
}
var file_bot_proto_depIdxs = []int32{
	0, // 0: bot.Bot.Process:input_type -> bot.InboundMessage
	1, // 1: bot.Bot.Process:output_type -> bot.ReplyChunk
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bot_proto_init() }
func file_bot_proto_init() {
	if File_bot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bot_proto_rawDesc), len(file_bot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bot_proto_goTypes,
		DependencyIndexes: file_bot_proto_depIdxs,
		MessageInfos:      file_bot_proto_msgTypes,
	}.Build()
	File_bot_proto = out.File
	file_bot_proto_goTypes = nil
	file_bot_proto_depIdxs = nil
}
