// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: bot.proto

package botpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Bot_Process_FullMethodName = "/bot.Bot/Process"
)

// BotClient is the client API for Bot service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Bot is the LLM bot's gRPC service. The gateway calls it synchronously
// on the hot path; Kafka carries the same events for analytics only.
type BotClient interface {
	// Process receives one inbound WhatsApp message and streams reply tokens
	// back as they are generated by Ollama. The final chunk carries done=true.
	Process(ctx context.Context, in *InboundMessage, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReplyChunk], error)
}

type botClient struct {
	cc grpc.ClientConnInterface
}

func NewBotClient(cc grpc.ClientConnInterface) BotClient {
	return &botClient{cc}
}

func (c *botClient) Process(ctx context.Context, in *InboundMessage, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReplyChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Bot_ServiceDesc.Streams[0], Bot_Process_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InboundMessage, ReplyChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Bot_ProcessClient = grpc.ServerStreamingClient[ReplyChunk]

// BotServer is the server API for Bot service.
// All implementations must embed UnimplementedBotServer
// for forward compatibility.
//
// Bot is the LLM bot's gRPC service. The gateway calls it synchronously
// on the hot path; Kafka carries the same events for analytics only.
type BotServer interface {
	// Process receives one inbound WhatsApp message and streams reply tokens
	// back as they are generated by Ollama. The final chunk carries done=true.
	Process(*InboundMessage, grpc.ServerStreamingServer[ReplyChunk]) error
	mustEmbedUnimplementedBotServer()
}

// UnimplementedBotServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBotServer struct{}

func (UnimplementedBotServer) Process(*InboundMessage, grpc.ServerStreamingServer[ReplyChunk]) error {
	return status.Error(codes.Unimplemented, "method Process not implemented")
}
func (UnimplementedBotServer) mustEmbedUnimplementedBotServer() {}
func (UnimplementedBotServer) testEmbeddedByValue()             {}

// UnsafeBotServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BotServer will
// result in compilation errors.
type UnsafeBotServer interface {
	mustEmbedUnimplementedBotServer()
}

func RegisterBotServer(s grpc.ServiceRegistrar, srv BotServer) {
	// If the following call panics, it indicates UnimplementedBotServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Bot_ServiceDesc, srv)
}

func _Bot_Process_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InboundMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BotServer).Process(m, &grpc.GenericServerStream[InboundMessage, ReplyChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Bot_ProcessServer = grpc.ServerStreamingServer[ReplyChunk]

// Bot_ServiceDesc is the grpc.ServiceDesc for Bot service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bot_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bot.Bot",
	HandlerType: (*BotServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Process",
			Handler:       _Bot_Process_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "bot.proto",
}
